"""tenant chatwoot_agent_bot_id

Revision ID: 9bef0cf00d76
Revises: 769d0168bccb
Create Date: 2026-06-08 13:19:22.375428+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bef0cf00d76'
down_revision: Union[str, Sequence[str], None] = '769d0168bccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('chatwoot_agent_bot_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'chatwoot_agent_bot_id')
    # ### end Alembic commands ###
