"""initial schema

Revision ID: 769d0168bccb
Revises: 
Create Date: 2026-06-08 12:58:03.829916+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '769d0168bccb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('chatwoot_account_id', sa.BigInteger(), nullable=False),
    sa.Column('chatwoot_api_token_enc', sa.Text(), nullable=True),
    sa.Column('medusa_api_url', sa.Text(), nullable=True),
    sa.Column('medusa_api_key_enc', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=32), nullable=False),
    sa.Column('llm_model', sa.String(length=64), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('notify_admin_on_message', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chatwoot_account_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('chatwoot_contact_id', sa.BigInteger(), nullable=False),
    sa.Column('medusa_customer_id', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=8), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chatwoot_contact_id', name='uq_customer_tenant_chatwoot')
    )
    op.create_index('ix_customers_email', 'customers', ['tenant_id', 'email'], unique=False)
    op.create_index('ix_customers_tenant', 'customers', ['tenant_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('chatwoot_conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bot_turn_count', sa.Integer(), nullable=False),
    sa.Column('last_bot_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'chatwoot_conversation_id', name='uq_conv_tenant_chatwoot')
    )
    op.create_index('ix_conversations_customer', 'conversations', ['customer_id'], unique=False)
    op.create_index('ix_conversations_status', 'conversations', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_conversations_tenant', 'conversations', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_call_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('chatwoot_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_conv_time', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('ix_messages_tenant_time', 'messages', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_tenant_time', table_name='messages')
    op.drop_index('ix_messages_conv_time', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversations_tenant', table_name='conversations')
    op.drop_index('ix_conversations_status', table_name='conversations')
    op.drop_index('ix_conversations_customer', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_customers_tenant', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_table('customers')
    op.drop_table('tenants')
    # ### end Alembic commands ###
